var hobby_cards_db = [
	["@Painting"],
	[
		"Mona Lisa",
		"MonaLisa.jpg",
		[640, 955, 0, -20],
		"<h5>Artist</h5>Leonardo da Vinci",
		"<h5>Year</h5>c. 1503-1506, perhaps continuing until c. 1517",
		"<h5>Medium</h5>Oil on poplar panel",
		"<h5>Subject</h5>Lisa del Giocondo",
		"<h5>Dimensions</h5>77 cm x 53 cm (30 in x 21 in)",
		"<h5>Location</h5>Louvre, Paris",
		"The Mona Lisa (/ˌmoʊnə 'li:sə/ MOH-nə LEE-sə; Italian: Gioconda [dʒo'konda] or Monna Lisa ['mɔnna 'li:za]; French: Joconde [ʒɔkɔ̃d]) is a half-length portrait painting by Italian artist Leonardo da Vinci. Considered an archetypal masterpiece of the Italian Renaissance, it has been described as &quot;the best known, the most visited, the most written about, the most sung about, [and] the most parodied work of art in the world&quot;. The painting's novel qualities include the subject's enigmatic expression, monumentality of the composition, the subtle modelling of forms, and the atmospheric illusionism.",
		"The painting has been traditionally considered to depict the Italian noblewoman, Lisa del Giocondo. It is painted in oil on a white Lombardy poplar panel. Leonardo never gave the painting to the Giocondo family, and it is believed he later left it in his will to his favored apprentice Salaì. It was believed to have been painted between 1503 and 1506; however, Leonardo may have continued working on it as late as 1517. It was acquired by King Francis I of France and is now the property of the French Republic. It has been on permanent display at the Louvre in Paris since 1797.",
		"The Mona Lisa is one of the most valuable paintings in the world. It holds the Guinness World Record for the highest known painting insurance valuation in history at US$100 million in 1962, equivalent to $1 billion as of 2023.",
		"The Mona Lisa bears a strong resemblance to many Renaissance depictions of the Virgin Mary, who was at that time seen as an ideal for womanhood. The woman sits markedly upright in a &quot;pozzetto&quot; armchair with her arms folded, a sign of her reserved posture. Her gaze is fixed on the observer. The woman appears alive to an unusual extent, which Leonardo achieved by his method of not drawing outlines (sfumato). The soft blending creates an ambiguous mood &quot;mainly in two features: the corners of the mouth, and the corners of the eyes&quot;.",
		"The painting was one of the first Italian portraits to depict the sitter in front of an imaginary landscape, and Leonardo was one of the first painters to use aerial perspective. The enigmatic woman is portrayed seated in what appears to be an open loggia with dark pillar bases on either side. Behind her, a vast landscape recedes to icy mountains, winding paths, and a distant bridge, giving only the slightest indications of human presence. Leonardo has chosen to place the horizon line not at the neck, as he did with Ginevra de' Benci, but on a level with the eyes, thus linking the figure with the landscape and emphasizing the mysterious nature of the painting. The bridge in the background was identified by Silvano Vincenti as the four-arched Romito di Laterina bridge from Etruscan-Roman times near Laterina, Arezzo over the Arno River. Other bridges with similar arches suggested as possible locations had more arches.",
		"Mona Lisa has no clearly visible eyebrows or eyelashes, although Vasari describes the eyebrows in detail. In 2007, French engineer Pascal Cotte announced that his ultra-high-resolution scans of the painting provide evidence that Mona Lisa was originally painted with eyelashes and eyebrows, but that these had gradually disappeared over time, perhaps because of overcleaning. Cotte discovered that the painting had been reworked several times, with changes made to the size of the face and the direction of gaze. He also found that in one layer the subject was depicted wearing numerous hairpins and a headdress adorned with pearls which was later scrubbed out and overpainted.",
		"Source: https://en.wikipedia.org/wiki/Mona_Lisa"
	],
	[
		"The Starry Night",
		"TheStarryNight.jpg",
		[640, 505],
		"<h5>Artist</h5>Vincent van Gogh",
		"<h5>Year</h5>1889",
		"<h5>Medium</h5>Oil on canvas",
		"<h5>Dimensions</h5>73.7 cm × 92.1 cm (29.01 in × 36.26 in)",
		"<h5>Location</h5>Museum of Modern Art, New York",
		"The Starry Night (Dutch: De sterrennacht) is an oil-on-canvas painting by the Dutch Post-Impressionist painter Vincent van Gogh. Painted in June 1889, it depicts the view from the east-facing window of his asylum room at Saint-Rémy-de-Provence, just before sunrise, with the addition of an imaginary village. It has been in the permanent collection of the Museum of Modern Art in New York City since 1941, acquired through the Lillie P. Bliss Bequest. Widely regarded as Van Gogh's magnum opus. The Starry Night is one of the most recognizable paintings in Western art.",
		"Although The Starry Night was painted during the day in Van Gogh's ground-floor studio, it would be inaccurate to state that the picture was painted from memory. The view has been identified as the one from his bedroom window, facing east, a view which Van Gogh painted variations of no fewer than twenty-one times, including The Starry Night. &quot;Through the iron-barred window&quot;, he wrote to his brother, Theo, around 23 May 1889, &quot;I can see an enclosed square of wheat ... above which, in the morning, I watch the sun rise in all its glory.&quot;",
		"Van Gogh depicted the view at different times of the day and under various weather conditions, such as the sunrise, moonrise, sunshine-filled days, overcast days, windy days, and one day with rain. While the hospital staff did not allow Van Gogh to paint in his bedroom, he was able there to make sketches in ink or charcoal on paper; eventually, he would base newer variations on previous versions. The pictorial element uniting all these paintings is the diagonal line coming in from the right depicting the low rolling hills of the Alpilles mountains. In fifteen of the twenty-one versions, cypress trees are visible beyond the far wall enclosing the wheat field. Van Gogh exaggerated their size in six of these paintings, most notably in Wheat Field with Cypresses and The Starry Night, bringing the trees closer to the picture plane.",
		"The Starry Night is the only nocturne in the series of views from his bedroom window. In early June, Vincent wrote to Theo, &quot;This morning I saw the countryside from my window a long time before sunrise with nothing but the morning star, which looked very big&quot;. Researchers have determined that Venus (sometimes referred to as the &quot;morning star&quot;) was indeed visible at dawn in Provence in the spring of 1889 and was at that time nearly as bright as possible. So, the brightest &quot;star&quot; in the painting, just to the viewer's right of the cypress tree, is Venus.",
		"Source: https://en.wikipedia.org/wiki/The_Starry_Night"
	],
	[
		"Guernica",
		"Guernica.jpg",
		[640, 240],
		"<h5>Artist</h5>Pablo Picasso",
		"<h5>Year</h5>1937",
		"<h5>Medium</h5>Oil on canvas",
		"<h5>Movement</h5>Cubism, Surrealism",
		"<h5>Dimensions</h5>349.3 cm × 776.6 cm (137.4 in × 305.5 in)",
		"<h5>Location</h5>Museo Reina Sofía, Madrid, Spain",
		"Guernica (Spanish: [ɡeɾˈnika]; Basque: [ɡernika]) is a large 1937 oil painting by Spanish artist Pablo Picasso. It is one of his best-known works, regarded by many art critics as the most moving and powerful anti-war painting in history. It is exhibited in the Museo Reina Sofía in Madrid.",
		"The grey, black, and white painting, on a canvas 3.49 meters (11 ft 5 in) tall and 7.76 meters (25 ft 6 in) across, portrays the suffering wrought by violence and chaos. Prominently featured in the composition are a gored horse, a bull, screaming women, a dead baby, a dismembered soldier, and flames.",
		"Picasso painted Guernica at his home in Paris in response to the 26 April 1937 bombing of Guernica, a town in the Basque Country in northern Spain that was bombed by Nazi Germany and Fascist Italy at the request of the Spanish Nationalists. Upon completion, Guernica was exhibited at the Spanish display at the 1937 Paris International Exposition and then at other venues around the world. The touring exhibition was used to raise funds for Spanish war relief. The painting soon became famous and widely acclaimed, helping to bring worldwide attention to the Spanish Civil War that took place from 1936 to 1939.",
		"Guernica was painted using a matte house paint specially formulated at Picasso's request to have the least possible gloss. American artist John Ferren assisted him in preparing the monumental canvas, and photographer Dora Maar, who had been working with Picasso since mid-1936 photographing his studio and teaching him the technique of camera less photography, documented its creation. Apart from their documentary and publicity value, Maar's photographs &quot;helped Picasso to eschew color and give the work the black-and-white immediacy of a photograph&quot;, according to art historian John Richardson.",
		"According to scholar Beverly Ray, the following list of interpretations reflects the general consensus of historians: &quot;The shape and posture of the bodies express protest&quot;; &quot;Picasso uses black, white, and grey paint to set a somber mood and express pain and chaos&quot;; &quot;flaming buildings and crumbling walls not only express the destruction of Guernica, but reflect the destructive power of civil war&quot;; &quot;the newspaper print used in the painting reflects how Picasso learned of the massacre&quot;; &quot;The light bulb in the painting represents the sun&quot;; and &quot;The broken sword near the bottom of the painting symbolizes the defeat of the people at the hand of their tormentors&quot;.",
		"Art historian and curator W. J. H. B. Sandberg argued in Daedalus in 1960 that Picasso pioneered a “new language” combining expressionistic and cubist techniques in Guernica. Sandberg wrote that Guernica conveyed an “expressionistic message” in its focus on the inhumanity of the air raid, while using &quot;the language of cubism&quot;. For Sandberg, the work's defining cubist features included its use of diagonals, which rendered the painting's setting &quot;ambiguous, unreal, inside and outside at the same time&quot;. In 2016, the British art critic Jonathan Jones called the painting a &quot;Cubist apocalypse&quot; and stated that Picasso &quot;was trying to show the truth so viscerally and permanently that it could outstare the daily lies of the age of dictators&quot;.",
		"Source: https://en.wikipedia.org/wiki/Guernica_(Picasso)"
	],
	[
		"Girl with a Pearl Earring",
		"GirlwithaPearlEarring.jpg",
		[640, 851, 0, -10],
		"<h5>Artist</h5>Johannes Vermeer",
		"<h5>Year</h5>c. 1665",
		"<h5>Type</h5>Tronie",
		"<h5>Medium</h5>Oil on canvas",
		"<h5>Movement</h5>Dutch Golden Age painting",
		"<h5>Dimensions</h5>44.5 cm × 39 cm (17.5 in × 15 in)",
		"<h5>Location</h5>Mauritshuis, The Hague, Netherlands",
		"Girl with a Pearl Earring (Dutch: Meisje met de parel) is an oil painting by Dutch Golden Age painter Johannes Vermeer, dated c. 1665. Going by various names over the centuries, it became known by its present title towards the end of the 20th century after the earring worn by the girl portrayed there. The work has been in the collection of the Mauritshuis in The Hague since 1902 and has been the subject of various literary and cinematic treatments.",
		"The painting is a tronie, the Dutch 17th-century description of a &quot;head&quot; that was not meant to be a portrait. It depicts a European girl wearing &quot;exotic dress&quot;, an &quot;oriental turban&quot;, and what appears to be a very large pearl as an earring. The subject of the painting is unknown, with it being possible either that she was a real model, or that Vermeer created a more generalized and mysterious woman, perhaps representing a Sibyl or biblical figure. There has been speculation that she is the artist's eldest daughter, Maria, though this has been dismissed as an anachronism by some art historians.",
		"The work is oil on canvas and is 44.5 cm (17.5 in) high and 39 cm (15 in) wide. It is signed &quot;IVMeer&quot; but not dated. It is estimated to have been painted around 1665.",
		"After the most recent restoration of the painting in 1994, the subtle color scheme and the intimacy of the girl's gaze toward the viewer have been greatly enhanced. During the restoration, it was discovered that the dark background, today somewhat mottled, was originally a deep enamel-like green. This effect was produced by applying a thin transparent layer of paint—a glaze—over the black background seen now. However, the two organic pigments of the green glaze, indigo and weld, have faded. In 2014, Dutch astrophysicist Vincent Icke raised doubts about the material of the earring and argued that it looks more like polished tin than pearl on the grounds of the specular reflection, the pear shape, and the large size of the earring.",
		"In February-March 2018 an international team of art experts spent two weeks studying the painting in a specially constructed glass workshop in the museum, open to observation by the public. The non-invasive research project included removing the work from its frame for study with microscopes, X-ray equipment and a special scanner to learn more about the methods and materials used by Vermeer. The project, with the name The Girl in the Spotlight, was headed by Abbie Vandivere, conservator at the Mauritshuis, and results were published by the Mauritshuis.",
		"Source: https://en.wikipedia.org/wiki/Girl_with_a_Pearl_Earring"
	],
	[
		"The Persistence of Memory",
		"ThePersistenceofMemory.jpg",
		[640, 366],
		"<h5>Artist</h5>Salvador Dalí",
		"<h5>Year</h5>c. 1931",
		"<h5>Medium</h5>Oil on canvas",
		"<h5>Movement</h5>Surrealism",
		"<h5>Dimensions</h5>24 cm × 33 cm (9.5 in × 13 in)",
		"<h5>Location</h5>Museum of Modern Art, New York City",
		"The Persistence of Memory (Catalan: La persistència de la memòria) is a 1931 painting by artist Salvador Dalí and one of the most recognizable works of Surrealism. First shown at the Julien Levy Gallery in 1932, since 1934 the painting has been in the collection of the Museum of Modern Art (MoMA) in New York City, which received it from an anonymous donor. It is widely recognized and frequently referred to in popular culture, and sometimes referred to by more descriptive titles, such as &quot;Melting Clocks&quot;, &quot;The Soft Watches&quot; or &quot;The Melting Watches&quot;.",
		"The well-known surrealist piece introduced the image of the soft melting pocket watch. It epitomizes Dalí's theory of &quot;softness&quot; and &quot;hardness&quot;, which was central to his thinking at the time. As Dawn Adès wrote, &quot;The soft watches are an unconscious symbol of the relativity of space and time, a Surrealist meditation on the collapse of our notions of a fixed cosmic order&quot;. This interpretation suggests that Dalí was incorporating an understanding of the world introduced by Albert Einstein's theory of special relativity. Asked by Ilya Prigogine whether this was in fact the case, Dalí replied that the soft watches were not inspired by the theory of relativity, but by the surrealist perception of a Camembert melting in the sun.",
		"It is possible to recognize a human figure in the middle of the composition, in the strange &quot;monster&quot; (with much texture near its face, and much contrast and tone in the picture) that Dalí used in several contemporary pieces to represent himself – the abstract form becoming something of a self-portrait, reappearing frequently in his work. The creature seems to be based on a figure from the Paradise section of Hieronymus Bosch's The Garden of Earthly Delights, which Dalí had studied. It can be read as a &quot;fading&quot; creature, one that often appears in dreams where the dreamer cannot pinpoint the creature's exact form and composition. One can observe that the creature has one closed eye with several eyelashes, suggesting that the creature is also in a dream state. The iconography may refer to a dream that Dalí himself had experienced, and the clocks may symbolize the passing of time as one experiences it in sleep or the persistence of time in the eyes of the dreamer.",
		"The orange clock at the bottom left of the painting is covered in ants. Dalí often used ants in his paintings as a symbol of decay. Another insect that is present in the painting is a fly, which sits on the watch that is next to the orange watch. The fly appears to be casting a human shadow as the sun hits it. The Persistence of Memory employs &quot;the exactitude of realist painting techniques&quot; to depict imagery more likely to be found in dreams than in waking consciousness.",
		"The craggy rocks to the right represent a tip of Cap de Creus peninsula in north-eastern Catalonia. Many of Dalí's paintings were inspired by the landscapes of his life in Catalonia. The strange and foreboding shadow in the foreground of this painting is a reference to Puig Pení.",
		"Source: https://en.wikipedia.org/wiki/The_Persistence_of_Memory"
	],
	[
		"Water Lilies",
		"WaterLilies.jpg",
		[640, 629],
		"<h5>Artist</h5>Claude Monet",
		"<h5>Year</h5>1899",
		"<h5>Medium</h5>Oil on canvas",
		"<h5>Dimensions</h5>90 cm × 90 cm (35.4 in × 35.4 in)",
		"<h5>Location</h5>Princeton University Art Museum",
		"Water Lilies (French: Nymphéas [nɛ̃.fe.a]) is a series of approximately 250 oil paintings by French Impressionist Claude Monet (1840–1926). The paintings depict his flower garden at his home in Giverny and were the main focus of his artistic production during the last thirty years of his life. Many of the works were painted while Monet suffered from cataracts.",
		"Monet's long-standing preference for producing and exhibiting a series of paintings related by subject and perspective began in 1889, with at least ten paintings done at the Valley of the Creuse, which were shown at the Galerie Georges Petit. Among his other famous series are his Haystacks.",
		"As part of his extensive gardening plans at Giverny, Monet had a pond dug in his garden and planted with lilies in 1893. He painted the subject in 1899, and thereafter it dominated his art. He worked continuously for more than twenty years on a large-scale decorative series, attempting to capture every observation, impression, and reflection of the flowers and water. The series captures the blooms at different times of the day, and under different atmospheric conditions. After much hesitation, Monet exhibited a group of 48 water-lily paintings in 1909 at the Paris gallery of his art dealer, Paul Durand-Ruel. The series became an enormous financial, popular, and critical hit. By the mid-1910s, Monet had achieved a completely new, fluid, and somewhat audacious style of painting in which the water-lily pond became the point of departure for an almost abstract art.",
		"During the 1920s, the state of France built a pair of oval rooms at the Musée de l'Orangerie as a permanent home for eight water lily murals by Monet. The exhibit opened to the public on 16 May 1927, a few months after Monet's death. Sixty water lily paintings from around the globe were assembled for a special exhibition at the Musée de l'Orangerie in 1999.",
		"Source: https://en.wikipedia.org/wiki/Water_Lilies_(Monet_series), https://en.wikipedia.org/wiki/Water_Lilies_(Monet_series)"
	],
	[
		"Almond Blossoms",
		"AlmondBlossoms.jpg",
		[640, 506],
		"<h5>Artist</h5>Almond Blossoms",
		"<h5>Year</h5>1890",
		"<h5>Medium</h5>Oil on canvas",
		"<h5>Dimensions</h5>73.5 cm × 92 cm (28.9 in × 36 in)",
		"<h5>Location</h5>Van Gogh Museum, Amsterdam",
		"Almond Blossoms is a group of several paintings made in 1888 and 1890 by Vincent van Gogh in Arles and Saint-Rémy, southern France of blossoming almond trees. Flowering trees were special to van Gogh. They represented awakening and hope. He enjoyed them aesthetically and found joy in painting flowering trees. The works reflect the influence of Impressionism, Divisionism, and Japanese woodcuts. Almond Blossom was made to celebrate the birth of his nephew and namesake, son of his brother Theo and sister-in-law Jo.",
		"When van Gogh arrived in Arles in March 1888 fruit trees in the orchards were about to bloom. The blossoms of the apricot, peach and plum trees motivated him, and within a month he had created fourteen paintings of blossoming fruit trees. Excited by the subject matter, van Gogh completed nearly one painting a day.",
		"Van Gogh's work reflected his interest in Japanese wood block prints. Hiroshige's Plum Park in Kameido demonstrates portrayal of beautiful subject matter with flat patterns of colors and no shadow. Van Gogh used the term Japonaiserie to express this influence; he collected hundreds of Japanese prints and likened the works of the great Japanese artists, like Hiroshige, to those of Rembrandt, Hals, and Vermeer. Hiroshige was one of the last great masters of the Japanese genre called ukiyo-e. Van Gogh integrated some of the technical aspects of ukiyo-e into his work as his two 1887 homages to Hiroshige demonstrates.",
		"In Art Inspiring Transmutations of Life, Bruce Ross evaluates the Impressionists' effect on van Gogh's work, Van Gogh's bright Sprig of Flowering Almond in a Glass embodies these streams* while exploring Japanese aesthetic values. A broken-off sprig is set in a simple glass. The sprig is highlighted by a red line along the beige wall and lavish empty space. There is no formal decorative intent. Van Gogh's name, also in bright red, hovers above a sprig in the upper left as if a symbol of hope. Van Gogh has transformed the still life with the help of these values. He has imbued a form predicated on death to one focused on life and possibility. His use of bright color reflects this. There is an individual, and hence essential, character to his subject, a sprig of almond buds and opening blossoms. This still life resembles the Japanese art of flower arrangement, ikebana, in its simplicity and evoked hopefulness as well as in its formal use of empty space.",
		"The composition is unlike any other of van Gogh's paintings. The branches of the almond tree seem to float against the blue sky and fill the picture plane. The close-up of the branches brings to mind Delacroix's proposition that &quot;even a part of a thing is kind of a complete entity in itself.&quot; Dark lines outline the branches. This is a feature that Van Gogh had admired in Japanese floral studies that, for example, may depict a portion of a stalk of bamboo in an empty space. The bright color is reflective of the paintings made in Arles and the transformational work van Gogh had on the still life genre.",
		"Source: https://en.wikipedia.org/wiki/Almond_Blossoms"
	],
	[
		"Lady with an Ermine",
		"LadywithanErmine.jpg",
		[640, 860, 0, -15],
		"<h5>Artist</h5>Leonardo da Vinci",
		"<h5>Year</h5>1489–1491",
		"<h5>Medium</h5>Oil on walnut panel",
		"<h5>Subject</h5>Cecilia Gallerani",
		"<h5>Dimensions</h5>54 cm × 39 cm (21 in × 15 in)",
		"<h5>Location</h5>Czartoryski Museum, Kraków, Poland",
		"The Lady with an Ermine is a portrait painting widely attributed to the Italian Renaissance artist Leonardo da Vinci. Dated to c. 1489–1491, the work is painted in oils on a panel of walnut wood. Its subject is Cecilia Gallerani, a mistress of Ludovico Sforza (&quot;Il Moro&quot;), Duke of Milan; Leonardo was painter to the Sforza court in Milan at the time of its execution. It is the second of only four surviving portraits of women painted by Leonardo, the others being Ginevra de' Benci, La Belle Ferronnière and the Mona Lisa.",
		"The painting was executed in oils on a somewhat small, 54 × 39 cm (21 × 15 in) walnut wood panel. It depicts a half-height woman turned toward her right at a three-quarter angle, but with her face turned toward her left. The animal in her arms twists in a similar manner, resulting in considerable contrapposto with the lady, a technique Leonardo explored earlier with the angel in the Virgin of the Rocks. The work is prepared with a layer of white gesso and a layer of brownish underpaint. In general, the paint is evenly applied akin to the Mona Lisa, though certain areas of the lady's skin are more layered. Also present are the subtle remains of spolvero (in the outline of the face and head), underdrawing (in the right arm, right hand, left hand, top of nose and edge of the hair), and fingerprints (the face and animal's head), the latter of which are particularly common in Leonardo's paintings. It is made from a single piece of walnut wood; Leonardo recommended, and favored walnut wood, though it was not commonly used by other artists in Lombardy. The wood is thin (about 4–5 millimetres (0.16–0.20 in)) and is most likely from the same tree as the wood for his later portrait, La Belle Ferronnière. The Lady with an Ermine is also connected to La Belle Ferronnière, as well as Leonardo's earlier Portrait of a Musician, due to the three paintings including black backgrounds.",
		"The subject has been identified with reasonable certainty as Cecilia Gallerani, the mistress of Leonardo's Milanese employer, Ludovico Sforza. She looks to her left at something out of frame, toward the light, where the biographer Walter Isaacson suggests Ludovico is. Following the marriage of Isabella of Aragon, Duchess of Milan and Gian Galeazzo Sforza, her 'Spanish style' dress would have been particularly fashionable. She has a silk sbernia on over her left shoulder, though Leonardo has simplified the traditional manner of wearing—where it would be draped over both shoulders—potentially to avoid too much complication in the various elements of the painting. Her right shoulder shows an ornately embroidered gold band over a velvet dress. Again, Leonardo has simplified the design, by having the left shoulder band covered by the sbernia, so as to not take away from the animal's detailed head. Her coiffure, known as a coazone, confines her hair smoothly to her head with two bands of it bound on either side of her face and a long plait at the back. Her hair is held in place by a fine gauze veil with a woven border of gold-wound threads, a black band, and a sheath over the plait.",
		"As in many of Leonardo's paintings, the composition comprises a pyramidic spiral and the sitter is caught in the motion of turning to her left, reflecting Leonardo's lifelong preoccupation with the dynamics of movement. The three-quarter profile portrait was one of his many innovations. Il Moro's court poet, Bernardo Bellincioni, was the first to propose that Cecilia was poised as if listening to an unseen speaker. This work shows Leonardo's expertise in painting the human form. The artist painted Cecilia's outstretched hand with a lot of detail, including the shape of each fingernail, the lines around her knuckles, and even the way the tendon in her bent finger moved as it bent.",
		"Source: https://en.wikipedia.org/wiki/Lady_with_an_Ermine"
	],
	[
		"The School of Athens",
		"TheSchoolofAthens.jpg",
		[640, 497],
		"<h5>Artist</h5>Raphael",
		"<h5>Year</h5>1509–1511",
		"<h5>Type</h5>Fresco",
		"<h5>Dimensions</h5>500 cm × 770 cm (200 in × 300 in)",
		"<h5>Location</h5>Apostolic Palace, Vatican City",
		"The School of Athens (Italian: Scuola di Atene) is a fresco by the Italian Renaissance artist Raphael. The fresco was painted between 1509 and 1511 as a part of Raphael's commission to decorate the rooms now known as the Stanze di Raffaello, in the Apostolic Palace in the Vatican. It depicts a congregation of philosophers, mathematicians, and scientists from Ancient Greece, including Plato, Aristotle, Pythagoras, Archimedes, Heraclitus and Zarathustr the Iranian prophet. The Italian artists Leonardo da Vinci and Michelangelo are also featured in the painting, shown as Plato and Heraclitus respectively.",
		"The painting notably features accurate perspective projection, a defining characteristic of the Renaissance era. Raphael learned perspective from Leonardo, whose role as Plato is central in the painting. The themes of the painting, such as the rebirth of Ancient Greek philosophy and culture in Europe (along with Raphael's work) were inspired by Leonardo's individual pursuits in theatre, engineering, optics, geometry, physiology, anatomy, history, architecture, and art.",
		"The School of Athens is regarded as one of Raphael's best-known works and has been described as &quot;Raphael's masterpiece and the perfect embodiment of the classical spirit of the Renaissance&quot;.",
		"The School of Athens is one of a group of four main frescoes on the walls of the Stanza (those on either side centrally interrupted by windows) that depict distinct branches of knowledge. Each theme is identified above by a separate tondo containing a majestic female figure seated in the clouds, with putti bearing the phrases: &quot;Seek Knowledge of Causes&quot;, &quot;Divine Inspiration&quot;, &quot;Knowledge of Things Divine&quot; (Disputa), &quot;To Each What Is Due&quot;. Accordingly, the figures on the walls below exemplify philosophy, poetry (including music), theology, and justice.[4][5] The traditional title is not Raphael's. The subject of the painting is philosophy, or at least ancient Greek philosophy, and its overhead tondo-label, &quot;Causarum Cognitio&quot;, tells us what kind, as it appears to echo Aristotle's emphasis on wisdom as knowing why, hence knowing the causes, in Metaphysics Book I and Physics Book II. Indeed, Plato and Aristotle appear to be the central figures in the scene. However, many of the philosophers depicted sought knowledge of first causes. Many lived before Plato and Aristotle, and hardly a third were Athenians. The architecture contains Roman elements, but the general semi-circular setting having Plato and Aristotle at its centre might be alluding to Pythagoras' monad.",
		"In the center of the fresco, at its architecture's central vanishing point, are the two undisputed main subjects: Plato on the left and Aristotle, his student, on the right. Both figures hold contemporary (of the time), bound copies of their books in their left hands, while gesturing with their right. Plato holds Timaeus and Aristotle holds his Nicomachean Ethics. Plato is depicted as old, grey, and bare-foot. By contrast, Aristotle, slightly ahead of him, is in mature manhood, wearing sandals and gold-trimmed robes, and the youth about them seem to look his way. In addition, these two central figures gesture along different dimensions: Plato vertically, upward along the picture-plane, into the vault above; Aristotle on the horizontal plane at right-angles to the picture-plane (hence in strong foreshortening), initiating a flow of space toward viewers.",
		"It is popularly thought that their gestures indicate central aspects of their philosophies, for Plato, his Theory of Forms, and for Aristotle, an emphasis on concrete particulars. Many interpret the painting to show a divergence of the two philosophical schools. Plato argues a sense of timelessness whilst Aristotle investigates the physicality of life and the present realm.",
		"The building is in the shape of a Greek cross, which some have suggested was intended to show a harmony between pagan philosophy and Christian theology (see Christianity and Paganism and Christian philosophy). The architecture of the building was inspired by the work of Bramante, who, according to Vasari, helped Raphael with the architecture in the picture. The resulting architecture was similar to the then new St. Peter's Basilica.",
		"There are two sculptures in the background. The one on the left is the god Apollo, God of light, archery and music, holding a lyre. The sculpture on the right is Athena, goddess of wisdom, in her Roman guise as Minerva.",
		"Source: https://en.wikipedia.org/wiki/The_School_of_Athens"
	],
	[
		"Ginevra de' Benci",
		"GinevradeBenci.jpg",
		[640, 678],
		"<h5>Artist</h5>Leonardo da Vinci",
		"<h5>Year</h5>c.1474–1478",
		"<h5>Type</h5>Oil on panel",
		"<h5>Dimensions</h5>38.1 cm × 37 cm (15.0 in × 15 in)",
		"<h5>Location</h5>National Gallery of Art, Washington, D.C.",
		"Ginevra de' Benci is a portrait painting by Leonardo da Vinci of the 15th-century Florentine aristocrat Ginevra de' Benci (born c. 1458). Exhibited at the National Gallery of Art in Washington, D.C. US; it is the only painting by Leonardo on public view in the Americas.",
		"Ginevra de' Benci, a well-known young Florentine woman, is universally considered to be the portrait's sitter. Leonardo painted the portrait in Florence between 1474 and 1478, possibly to commemorate Ginevra's marriage to Luigi di Bernardo Niccolini at the age of 16. More likely, it commemorates the engagement. Commonly, contemporary portraits of females were commissioned for either of two occasions: betrothal or marriage. Wedding portraits traditionally were created in pairs, with the woman on the right, facing left; since this portrait faces right, it more likely represents betrothal.",
		"The juniper bush that surrounds Ginevra's head and fills much of the background, serves more than mere decorative purposes. In Renaissance Italy, the juniper was regarded a symbol of female virtue, while the Italian word for juniper, ginepro, also makes a play on Ginevra's name.",
		"The imagery and text on the reverse of the panel—a juniper sprig encircled by a wreath of laurel and palm, memorialized by the Latin motto Virtvtem Forma Decorat (&quot;Beauty adorns virtue&quot;)—further support the identification of the portrait. The phrase is understood as symbolizing the intricate relationship between Ginevra's intellectual and moral virtue on the one hand, and her physical beauty on the other. The sprig of juniper, encircled by laurel and palm, suggests her name. The laurel and palm are in the personal emblem of Bernardo Bembo, a Venetian ambassador to Florence whose platonic relationship with Ginevra is revealed in poems exchanged between them. Infrared examination has revealed Bembo's motto &quot;Virtue and Honor&quot; beneath Ginevra's, making it likely that Bembo was somehow involved in the commission of the portrait.",
		"The portrait is one of the highlights of the National Gallery of Art and is admired by many for its portrayal of Ginevra's temperament. Ginevra is beautiful, but austere; she has no hint of a smile and her gaze, although forward, seems indifferent to the viewer.",		
		"Source: https://en.wikipedia.org/wiki/Ginevra_de%27_Benci"
	],
	["@Music"],
	[
		"Ludwig van Beethoven",
		"Beethoven.jpg",
		[640, 800, 0, -15],
		"Ludwig van Beethoven (baptised 17 December 1770 – 26 March 1827) was a German composer and pianist. Beethoven remains one of the most admired composers in the history of Western music; his works rank among the most performed of the classical music repertoire and span the transition from the Classical period to the Romantic era in classical music. His career has conventionally been divided into early, middle, and late periods. His early period, during which he forged his craft, is typically considered to have lasted until 1802. From 1802 to around 1812, his middle period showed an individual development from the styles of Joseph Haydn and Wolfgang Amadeus Mozart, and is sometimes characterized as heroic. During this time, he began to grow increasingly deaf. In his late period, from 1812 to 1827, he extended his innovations in musical form and expression.",
		"Beethoven was born in Bonn. His musical talent was obvious at an early age. He was initially harshly and intensively taught by his father, Johann van Beethoven. Beethoven was later taught by the composer and conductor Christian Gottlob Neefe, under whose tutelage he published his first work, a set of keyboard variations, in 1783. He found relief from a dysfunctional home life with the family of Helene von Breuning, whose children he loved, befriended, and taught piano. At age 21, he moved to Vienna, which subsequently became his base, and studied composition with Haydn. Beethoven then gained a reputation as a virtuoso pianist, and was soon patronised by Karl Alois, Prince Lichnowsky for compositions, which resulted in his three Opus 1 piano trios (the earliest works to which he accorded an opus number) in 1795.",
		"His first major orchestral work, the First Symphony, premiered in 1800, and his first set of string quartets was published in 1801. Despite his hearing deteriorating during this period, he continued to conduct, premiering his Third and Fifth Symphonies in 1804 and 1808, respectively. His Violin Concerto appeared in 1806. His last piano concerto (No. 5, Op. 73, known as the Emperor), dedicated to his frequent patron Archduke Rudolf of Austria, premiered in 1811, without Beethoven as soloist. He was almost completely deaf by 1814, and he then gave up performing and appearing in public. He described his problems with health and his unfulfilled personal life in two letters, his Heiligenstadt Testament (1802) to his brothers and his unsent love letter to an unknown &quot;Immortal Beloved&quot; (1812).",
		"After 1810, increasingly less socially involved, Beethoven composed many of his most admired works, including later symphonies, mature chamber music and the late piano sonatas. His only opera, Fidelio, first performed in 1805, was revised to its final version in 1814. He composed Missa solemnis between 1819 and 1823 and his final Symphony, No. 9, one of the first examples of a choral symphony, between 1822 and 1824. Written in his last years, his late string quartets, including the Grosse Fuge, of 1825–1826 are among his final achievements.",
		"Source: https://en.wikipedia.org/wiki/Ludwig_van_Beethoven"
	],
	[
		"Frédéric Chopin",
		"Chopin.jpg",
		[640, 860, 0, -12],
		"Frédéric Chopin's Nocturne No. 21 in C minor, B. 108, WN 62, is a musical work for solo piano composed in 1847-1848. It was the last of Chopin's nocturnes to be published and was done so posthumously in 1938. It is famous for its striking simplicity and folk-like melody. Among the 21 nocturnes known to have been written by Chopin, this is one of the three that end in a minor key - the other two being No. 13 in C Minor and No. 9 in B Major.",
		"Frédéric Chopin wrote 21 nocturnes for solo piano between 1827 and 1846. They are generally considered among the finest short solo works for the instrument and hold an important place in contemporary concert repertoire. Although Chopin did not invent the nocturne, he popularized and expanded on it, building on the form developed by Irish composer John Field.",
		"By the time of Chopin's birth in 1810, John Field was already an accomplished composer. Eventually, the young Chopin became a great admirer of Field, taking some influence from the Irish composer's playing and composing technique. Chopin had composed five of his nocturnes before meeting Field for the first time.",
		"Chopin's nocturnes carry many similarities with those of Field while at the same time retaining a distinct, unique sound of their own. One aspect of the nocturne that Chopin continued from Field is the use of a song-like melody in the right hand. This is one of the most if not the most important features to the nocturne. The use of the melody as vocals bestowed a greater emotional depth to the piece, drawing the listener in to a greater extent. Along with the right-hand melody, Chopin continued the use of another nocturne &quot;necessity&quot;, that of playing broken chords on the left hand to act as the rhythm under his right-handed &quot;vocal&quot; melody. Another technique used by Field and continued by Chopin was the more extensive use of the pedal. By using the pedal more, the music gains more emotional expression through sustained notes, giving the piece an aura of drama. With these main attributes of the &quot;Field nocturne&quot; Chopin was inspired and expanded upon them to develop the &quot;Chopin nocturne&quot;.",
		"One of the greatest innovations made by Chopin to the nocturne was his use of a more freely flowing rhythm, a technique based on the classical music style. Also, Chopin further developed the structure of the nocturne, taking inspiration from the Italian and French opera arias, as well as the sonata form. Composer Franz Liszt even insisted that Chopin's nocturnes were influenced by Vincenzo Bellini's bel canto arias, a statement affirmed and echoed by many in the music world. A further innovation of Chopin's was his use of counterpoint to create tension in the nocturnes, a method that even further expanded the dramatic tone and feel of the piece itself. It was mainly through these themes of operatic influence, freer rhythms, and an expansion into more complex structures and melodic playing that Chopin made his mark on the nocturne. Many thinks of the &quot;Chopin nocturne&quot; as a mix between the form and structure of Field and the sound of Mozart, displaying a classic/romantic-influenced theme within the music.",
		"Please refer to the https://michaelkravchuk.com/wp-content/uploads/2021/09/Chopin-Nocturne-Op.-Post.pdf for sheet music.",
		"Source: https://en.wikipedia.org/wiki/Nocturne_in_C_minor,_Op._posth._(Chopin), https://en.wikipedia.org/wiki/Nocturnes_(Chopin)"
	],
	[
		"Wolfgang Amadeus Mozart",
		"WolfgangAmadeusMozart.jpg",
		[640, 928, 0, -20],
		"Wolfgang Amadeus Mozart (27 January 1756 – 5 December 1791) was a prolific and influential composer of the Classical period. Despite his short life, his rapid pace of composition resulted in more than 800 works of virtually every genre of his time. Many of these compositions are acknowledged as pinnacles of the symphonic, concertante, chamber, operatic, and choral repertoire. Mozart is widely regarded as among the greatest composers in the history of Western music, with his music admired for its &quot;melodic beauty, its formal elegance and its richness of harmony and texture&quot;",
		"Born in Salzburg, then in the Holy Roman Empire and currently in Austria, Mozart showed prodigious ability from his earliest childhood. Already competent on keyboard and violin, he composed from the age of five and performed before European royalty. His father took him on a grand tour of Europe and then three trips to Italy. At 17, he was a musician at the Salzburg court but grew restless and travelled in search of a better position.",
		"Mozart's music, like Haydn's, stands as an archetype of the Classical style. At the time he began composing, European music was dominated by the style galant, a reaction against the highly evolved intricacy of the Baroque. Progressively, and in large part at the hands of Mozart himself, the contrapuntal complexities of the late Baroque emerged once more, moderated and disciplined by new forms, and adapted to a new aesthetic and social milieu. Mozart was a versatile composer, and wrote in every major genre, including symphony, opera, the solo concerto, chamber music including string quartet and string quintet, and the piano sonata. These forms were not new, but Mozart advanced their technical sophistication and emotional reach. He almost single-handedly developed and popularized the Classical piano concerto. He wrote a great deal of religious music, including large-scale masses, as well as dances, divertimenti, serenades, and other forms of light entertainment.",
		"The central traits of the Classical style are all present in Mozart's music. Clarity, balance, and transparency are the hallmarks of his work, but simplistic notions of its delicacy mask the exceptional power of his finest masterpieces, such as the Piano Concerto No. 24 in C minor, K. 491; the Symphony No. 40 in G minor, K. 550; and the opera Don Giovanni.",
		"Source: https://en.wikipedia.org/wiki/Wolfgang_Amadeus_Mozart"
	],
	[
		"Johann Sebastian Bach",
		"Bach.jpg",
		[640, 788, 0, -20],
		"Johann Sebastian Bach (31 March [O.S. 21 March] 1685 – 28 July 1750) was a German composer and musician of the late Baroque period. He is known for his orchestral music such as the Brandenburg Concertos; instrumental compositions such as the Cello Suites; keyboard works such as the Goldberg Variations and The Well-Tempered Clavier; organ works such as the Schubler Chorales and the Toccata and Fugue in D minor; and vocal music such as the St Matthew Passion and the Mass in B minor. Since the 19th-century Bach revival, he has been generally regarded as one of the greatest composers in the history of Western music. He has been called the &quot;father of harmony&quot;.",
		"The Bach family already counted several composers when Johann Sebastian was born as the last child of a city musician, Johann Ambrosius, in Eisenach. After being orphaned at the age of 10, he lived for five years with his eldest brother Johann Christoph, after which he continued his musical education in Lüneburg. From 1703 he was back in Thuringia, working as a musician for Protestant churches in Arnstadt and Mühlhausen and, for longer stretches of time, at courts in Weimar, where he expanded his organ repertory, and Köthen, where he was mostly engaged with chamber music. From 1723, he was employed as Thomaskantor (cantor at St Thomas's) in Leipzig. There he composed music for the principal Lutheran churches of the city, and for its university's student ensemble Collegium Musicum. From 1726, he published some of his keyboard and organ music. In Leipzig, as had happened during some of his earlier positions, he had difficult relations with his employer, a situation that was little remedied when he was granted the title of court composer by his sovereign, Augustus III of Poland, in 1736. In the last decades of his life, he reworked and extended many of his earlier compositions. He died of complications after eye surgery in 1750 at the age of 65.",
		"Bach enriched established German styles through his mastery of counterpoint, harmonic, and motivic organisation, and his adaptation of rhythms, forms, and textures from abroad, particularly from Italy and France. Bach's compositions include hundreds of cantatas, both sacred and secular. He composed Latin church music, Passions, oratorios, and motets. He often adopted Lutheran hymns, not only in his larger vocal works, but for instance also in his four-part chorales and his sacred songs. He wrote extensively for organ and for other keyboard instruments. He composed concertos, for instance for violin and for harpsichord, and suites, as chamber music as well as for orchestra. Many of his works employ the genres of canon and fugue.",
		"Throughout the 18th century, Bach was primarily valued as an organist, while his keyboard music, such as The Well-Tempered Clavier, was appreciated for its didactic qualities. The 19th century saw the publication of some major Bach biographies, and by the end of that century all of his known music had been printed. Dissemination of scholarship on the composer continued through periodicals (and later also websites) exclusively devoted to him, and other publications such as the Bach-Werke-Verzeichnis (BWV, a numbered catalogue of his works) and new critical editions of his compositions. His music was further popularised through a multitude of arrangements, including the Air on the G String and &quot;Jesu, Joy of Man's Desiring&quot;, and of recordings, such as three different box sets with complete performances of the composer's oeuvre marking the 250th anniversary of his death.",
		"Source: https://en.wikipedia.org/wiki/Johann_Sebastian_Bach"
	],
	[
		"Joseph Haydn",
		"Haydn.jpg",
		[640, 800],
		"Franz Joseph Haydn (/ˈhaɪdən/ HY-dən, German: [ˈfʁants ˈjoːzɛf ˈhaɪdn̩]; 31 March[b] 1732 – 31 May 1809) was a German Austrian composer of the Classical period. He was instrumental in the development of chamber music such as the string quartet and piano trio.[2] His contributions to musical form have led him to be called &quot;Father of the Symphony&quot; and &quot;Father of the String Quartet&quot;.",
		"Haydn spent much of his career as a court musician for the wealthy Esterházy family at their Eszterháza Castle. Until the later part of his life, this isolated him from other composers and trends in music so that he was, as he put it, &quot;forced to become original&quot;. Yet his music circulated widely, and for much of his career he was the most celebrated composer in Europe.",
		"He was a friend and mentor of Mozart, a tutor of Beethoven, and the elder brother of composer Michael Haydn.",
		"Source: https://en.wikipedia.org/wiki/Joseph_Haydn"
	],
	[
		"Franz Schubert",
		"Schubert.jpg",
		[640, 780],
		"Franz Peter Schubert (German: [fʁants ˈpeːtɐ ˈʃuːbɐt]; 31 January 1797 – 19 November 1828) was an Austrian composer of the late Classical and early Romantic eras. Despite his short life, Schubert left behind a vast oeuvre, including more than 600 secular vocal works (mainly lieder), seven complete symphonies, sacred music, operas, incidental music, and a large body of piano and chamber music. His major works include the art songs Erlkönig, Gretchen am Spinnrade, Ave Maria; the Trout Quintet, the unfinished Symphony No. 8 in B minor, the &quot;Great&quot; Symphony No. 9 in C major, the String Quartet No. 14 &quot;Death and the Maiden&quot;, a String Quintet, the two sets of Impromptus for solo piano, the three last piano sonatas, the Fantasia in F minor for piano four hands, the opera Fierrabras, the incidental music to the play Rosamunde, and the song cycles Die schöne Müllerin, Winterreise and Schwanengesang.",
		"Born in the Himmelpfortgrund suburb of Vienna, Schubert showed uncommon gifts for music from an early age. His father gave him his first violin lessons and his elder brother gave him piano lessons, but Schubert soon exceeded their abilities. In 1808, at the age of eleven, he became a pupil at the Stadtkonvikt school, where he became acquainted with the orchestral music of Joseph Haydn, Wolfgang Amadeus Mozart, and Ludwig van Beethoven. He left the Stadtkonvikt at the end of 1813 and returned home to live with his father, where he began studying to become a schoolteacher. Despite this, he continued his studies in composition with Antonio Salieri and still composed prolifically. In 1821, Schubert was admitted to the Gesellschaft der Musikfreunde as a performing member, which helped establish his name among the Viennese citizenry. He gave a concert of his works to critical acclaim in March 1828, the only time he did so in his career. He died eight months later at the age of 31, the cause officially attributed to typhoid fever, but believed by some historians to be syphilis.",
		"Appreciation of Schubert's music while he was alive was limited to a relatively small circle of admirers in Vienna, but interest in his work increased greatly in the decades following his death. Felix Mendelssohn, Robert Schumann, Franz Liszt, Johannes Brahms and other 19th-century composers discovered and championed his works. Today, Schubert is ranked among the greatest composers in the history of Western classical music and his work continues to be admired and widely performed.",
		"Source: https://en.wikipedia.org/wiki/Franz_Schubert"
	],
	[
		"Pyotr Ilyich Tchaikovsky",
		"Tchaikovsky.jpg",
		[640, 780, 0, -10],
		"Pyotr Ilyich Tchaikovsky (/tʃaɪˈkɒfski/ chy-KOF-skee; 7 May 1840 – 6 November 1893) was a Russian composer of the Romantic period. He was the first Russian composer whose music would make a lasting impression internationally. Tchaikovsky wrote some of the most popular concert and theatrical music in the current classical repertoire, including the ballets Swan Lake and The Nutcracker, the 1812 Overture, his First Piano Concerto, Violin Concerto, the Romeo and Juliet Overture-Fantasy, several symphonies, and the opera Eugene Onegin.",
		"Although musically precocious, Tchaikovsky was educated for a career as a civil servant as there was little opportunity for a musical career in Russia at the time and no system of public music education. When an opportunity for such an education arose, he entered the nascent Saint Petersburg Conservatory, from which he graduated in 1865. The formal Western-oriented teaching that Tchaikovsky received there set him apart from composers of the contemporary nationalist movement embodied by the Russian composers of The Five with whom his professional relationship was mixed.",
		"Tchaikovsky's training set him on a path to reconcile what he had learned with the native musical practices to which he had been exposed from childhood. From that reconciliation, he forged a personal but unmistakably Russian style. The principles that governed melody, harmony, and other fundamentals of Russian music diverged from those that governed Western European music, which seemed to defeat the potential for using Russian music in large-scale Western composition or for forming a composite style, and it caused personal antipathies that dented Tchaikovsky's self-confidence. Russian culture exhibited a split personality, with its native and adopted elements having drifted apart increasingly since the time of Peter the Great. That resulted in uncertainty among the intelligentsia about the country's national identity, an ambiguity mirrored in Tchaikovsky's career.",
		"Source: https://en.wikipedia.org/wiki/Pyotr_Ilyich_Tchaikovsky"
	],
	[
		"Johannes Brahms",
		"Brahms.jpg",
		[640, 800, 0, -10],
		"Johannes Brahms (German: [joˈhanəs ˈbʁaːms]; 7 May 1833 – 3 April 1897) was a German composer, pianist, and conductor of the mid-Romantic period. Born in Hamburg into a Lutheran family, he spent much of his professional life in Vienna. He is sometimes grouped with Johann Sebastian Bach and Ludwig van Beethoven as one of the &quot;Three Bs&quot; of music, a comment originally made by the nineteenth-century conductor Hans von Bülow.",
		"Brahms composed for symphony orchestra, chamber ensembles, piano, organ, voice, and chorus. A virtuoso pianist, he premiered many of his own works. He worked with leading performers of his time, including the pianist Clara Schumann and the violinist Joseph Joachim (the three were close friends). Many of his works have become staples of the modern concert repertoire.",
		"Brahms has been considered both a traditionalist and an innovator, by his contemporaries and by later writers. His music is rooted in the structures and compositional techniques of the Classical masters. Embedded within those structures are deeply Romantic motifs. While some contemporaries found his music to be overly academic, his contribution and craftsmanship were admired by subsequent figures as diverse as Arnold Schoenberg and Edward Elgar. The detailed construction of Brahms's works was a starting point and an inspiration for a generation of composers.",
		"Source: https://en.wikipedia.org/wiki/Johannes_Brahms"
	],
	[
		"Felix Mendelssohn",
		"Mendelssohn.jpg",
		[640, 800, 0, -10],
		"Jakob Ludwig Felix Mendelssohn Bartholdy (3 February 1809 – 4 November 1847), widely known as Felix Mendelssohn, was a German composer, pianist, organist and conductor of the early Romantic period. Mendelssohn's compositions include symphonies, concertos, piano music, organ music and chamber music. His best-known works include the overture and incidental music for A Midsummer Night's Dream (which includes his &quot;Wedding March&quot;), the Italian Symphony, the Scottish Symphony, the oratorio St. Paul, the oratorio Elijah, the overture The Hebrides, the mature Violin Concerto, the String Octet, and the melody used in the Christmas carol &quot;Hark! The Herald Angels Sing&quot;. Mendelssohn's Songs Without Words are his most famous solo piano compositions.",
		"Mendelssohn's grandfather was the renowned Jewish philosopher Moses Mendelssohn, but Felix was initially raised without religion until he was baptised aged seven into the Reformed Christian church. He was recognised early as a musical prodigy, but his parents were cautious and did not seek to capitalise on his talent. His sister Fanny Mendelssohn received a similar musical education and was a talented composer and pianist in her own right; some of her early songs were published under her brother's name and her Easter Sonata was for a time mistakenly attributed to him after being lost and rediscovered in the 1970s.",
		"Mendelssohn enjoyed early success in Germany, and revived interest in the music of Johann Sebastian Bach, notably with his performance of the St Matthew Passion in 1829. He became well received in his travels throughout Europe as a composer, conductor and soloist; his ten visits to Britain – during which many of his major works were premiered – form an important part of his adult career. His essentially conservative musical tastes set him apart from more adventurous musical contemporaries such as Franz Liszt, Richard Wagner, Charles-Valentin Alkan and Hector Berlioz. The Leipzig Conservatory,[n 3] which he founded, became a bastion of this anti-radical outlook. After a long period of relative denigration due to changing musical tastes and antisemitism in the late 19th and early 20th centuries, his creative originality has been re-evaluated. He is now among the most popular composers of the Romantic era.",
		"Source: https://en.wikipedia.org/wiki/Felix_Mendelssohn"
	],
	[
		"Johann Strauss II",
		"Strauss.jpg",
		[640, 800, 0, -10],
		"Johann Baptist Strauss II (German: [ˈjoːhan bapˈtɪst ˈʃtʁaʊs]; 25 October 1825 – 3 June 1899), also known as Johann Strauss Jr., the Younger or the Son (German: Johann Strauß Sohn), was an Austrian composer of light music, particularly dance music and operettas as well as a violinist. He composed over 500 waltzes, polkas, quadrilles, and other types of dance music, as well as several operettas and a ballet. In his lifetime, he was known as &quot;The Waltz King&quot;, and was largely responsible for the popularity of the waltz in Vienna during the 19th century. Some of Johann Strauss's most famous works include &quot;The Blue Danube&quot;, &quot;Kaiser-Walzer&quot; (Emperor Waltz), &quot;Tales from the Vienna Woods&quot;, &quot;Frühlingsstimmen&quot;, and the &quot;Tritsch-Tratsch-Polka&quot;. Among his operettas, Die Fledermaus and Der Zigeunerbaron are the best known.",
		"Strauss was the son of Johann Strauss I and his first wife Maria Anna Streim. Two younger brothers, Josef and Eduard Strauss, also became composers of light music, although they were never as well known as their brother.",
		"Source: https://en.wikipedia.org/wiki/Johann_Strauss_II"
	],
	["@Craft"],
	[
		"Make Pan Flute by Straws",
		"MakePanFlutebyStraws.jpg",
		[640, 785],
		"<b>What you need</b>",
		"Straws - Your choice how many. We used six straw to get eight tubes because we used cut ends for some of the short ones.",
		"Tape - Your choice here too. Clear tape will do the job, but pretty tape will make it even more fun!",
		"<b>What you do</b>",
		"1. Cut the straws in all different sizes. It works best to plan out the order you want them if you're using different colored straws and then start cutting from longest to shortest. Use cut ends if you can for some of the shorter ones.",
		"<h5>C</h5>15.5 cm",
		"<h5>D</h5>13.8 cm",
		"<h5>E</h5>12.3 cm",
		"<h5>F</h5>11.6 cm",
		"<h5>G</h5>10.3 cm",
		"<h5>A</h5>9.2 cm",
		"<h5>B</h5>8.2 cm",
		"<h5>C</h5>7.7 cm",
		"2.	Lay a piece of tape down with the sticky side facing up. Begin placing the straws along it starting with the shortest straw so you make sure you have enough of it above and below the tape. Then line the rest up in order of length, being sure to keep the top edge as straight as possible.",
		"3.	Once the straws are placed, wrap the ends of the tape up and around the other side of the straws until the ends meet. Wrap it around a second time for extra strength, but this time in the opposite direction.",
		"4.	Have fun playing your pan flute! You can blow across the opening or down into the straws, but don't put your mouth on the straws or it won't work! Notice how each straw has a different pitch based on its length.",
		"<b>Let’s try</b>",
		"<img src='hobbycards/Ode-to-Joy.png' style='width:320;height:453;'>",
		"",
		"Source: https://lexington.macaronikid.com/articles/599e060ab2225771d7151637/make-your-own-pan-flute-with-straws, https://pianocoda.com/beethoven/ode-to-joy/"
	],
	[
		"Build Drums by Recycled Cans",
		"UseRecycledCanstoBuildDrums.jpg",
		[640, 604],
		"<b>Note: NOTE: Please never leave young children unattended with this tin can music craft. Some people are concerned about the dangers of balloons, others about the sharpness of the inside of the tin and others again, about the thing we added to make the tins SHAKE SHAKE SHAKE. So. Please take care!</b>",
		"<b>Tin Can Drums Materials</b>",
		"&#10003; a can per drum<br>&#10003; a balloon per drum<br>&#10003; elastic band<br>&#10003; something to make a shaker sound – e.g. rice, chickpeas, little stones<br>&#10003; scissors & drum sticks of sorts (we used chop sticks)",
		"<b>Tin Can Drums Steps</b>",
		"1.	Get all your materials ready. If you wish, you can sand down the inside of the can first. We used rice in one tin (lovely sound) and small pebbles in the other tin can – GREAT but NOISY sound……",
		"2.	Cut the end of your balloon.",
		"3.	Stretch your balloon over the tin can and secure in place with an elastic band. Ta da!!!",
		"4.	You tin can drum is FINISHED!! Yay! We did find that vigorous tin can drumming broke one of the balloons. But that is ok... whip it off and add another. Quickly done.",
		"Source: https://www.redtedart.com/tin-can-drums/"
	],
	[
		"Rubber Band Box Guitar",
		"RubberBandBoxGuitar.jpg",
		[640, 285, -70],
		"<b>Materials</b>",
		"&#10003; Four rubber bands of varying thickness but the same length<br>&#10003; Glue<br>&#10003; Packing tape (or other strong tape)<br>&#10003; Empty tissue box<br>&#10003; Scissors<br>&#10003; Two large craft sticks<br>&#10003; Empty paper towel tube",
		"<b>Preparation</b>",
		"&#10003; Remove the plastic inside the hole of the tissue box.<br>&#10003; Use the tape to attach the paper towel tube to one short end of the tissue box. Make sure it is lined up with the box’s hole.<br>&#10003; Glue a craft stick to each end of the hole in the tissue box. The sticks should be perpendicular to the direction of the hole and close to its edges. Allow the glue to dry.",
		"<b>Procedure</b>",
		"1.	Wrap each rubber band around the tissue box lengthwise so they rest on the craft sticks. The rubber bands can cross over the hole in the tissue box top, but they don’t need to as long as they’re resting on the craft sticks.",
		"2.	Hold your guitar by the paper towel roll, and gently pluck each rubber band. Do all of the rubber bands sound the same? If not, which makes a higher-pitch sound, the thin or thick rubber bands? In addition to sound, can you feel anything happening when you pluck the rubber bands?",
		"3.	Choose one rubber band and pluck it. Listen carefully to the sound it makes. Press your finger down on the rubber band so that it is pinched between your finger and one of the craft sticks. Does the sound change when your finger is pressed on the rubber band? If so, what changes about it?",
		"4.	Try pressing each rubber band down on the craft stick. Notice how this changes the sound the rubber band makes.",
		"5.	Extra: Try increasing the size of the tissue box hole. How does this change the sound?",
		"Source: https://www.scientificamerican.com/article/tune-up-your-rubber-band-guitar/"
	],
	[
		"Make Your Own Chess Set",
		"Chess.jpg",
		[640, 638],
		"20th July marks the date in 1924 when the International Chess Federation was established in Paris. World Chess Day (or International Chess Day) is now celebrated worldwide on this day.",
		"The easiest way to create your own paper chess set is to print off a printable template. There are plenty available across the Internet, including this fabulous one from the teacher and parent learning resource website Twinkl.",
		"You’ll just need to print off the patterns, carefully cut out each of them and then either Sellotape or glue them into shape.",
		"The website also offers other helpful printable resources, including a design your own chess piece activity sheet and a chess club resource pack which explains how each of the pieces moves and how to play.",
		"The Twinkl paper chess sets are great, but if you would like to make your pieces a little sturdier, you could mount 2D shapes on cardboard and then attach them to a cardboard base.",
		"Before you cut out each piece, add a small rectangle to the bottom of each of your paper and cardstock patterns. This way, you create a tab that can be folded back and used to attach your paper chess piece to a cardboard base.",
		"Source: https://navigator-business-optimizer.com/2021/07/fun-with-paper-make-your-very-own-chess-game-and-celebrate-the-world-chess-day/"
	],
	[
		"Draw a Comic Character",
		"ComicCharacter.jpg",
		[640, 290],
		"1.	Sketch a circle for the head.",
		"2.	Then, draw an oblong attached to it.",
		"3.	Sketch a vertical oblong for the body.",
		"4.	Sketch the extremities and the neck as lines showing the cartoon character’s position.",
		"5.	Sketch 4 lines in the face as guidelines for the eyes, nose, and mouth.",
		"6.	Draw the cheeks.",
		"7.	Draw the eyes, mouth, and ears. Experiment on the expressions shown through these facial parts.",
		"8.	Draw the hair as you like. You can also experiment on this.",
		"9.	Then draw the body and the clothes that you like the character to have.",
		"10. Erase the draft lines.",
		"11. Color",
		"Source: https://www.wikihow.com/Draw-Simple-Comic-Characters"
	],
	[
		"Bottle Cap Art",
		"BottleCapArt.jpg",
		[640, 409, -29],
		"Save all those plastic milk caps, bottle caps, and lids to make fun crafts",
		"Source: https://www.craftymorning.com/plastic-bottle-cap-lid-crafts-for-kids/"
	],
	["@Science"],
	[
		"Black hole",
		"Blackhole.jpg",
		[640, 515],
		"A black hole is a region of spacetime where gravity is so strong that nothing, including light and other electromagnetic waves, has enough energy to escape it. The theory of general relativity predicts that a sufficiently compact mass can deform spacetime to form a black hole. The boundary of no escape is called the event horizon. Although it has a great effect on the fate and circumstances of an object crossing it, it has no locally detectable features according to general relativity. In many ways, a black hole acts like an ideal black body, as it reflects no light. Moreover, quantum field theory in curved spacetime predicts that event horizons emit Hawking radiation, with the same spectrum as a black body of a temperature inversely proportional to its mass. This temperature is of the order of billionths of a kelvin for stellar black holes, making it essentially impossible to observe directly.",
		"Objects whose gravitational fields are too strong for light to escape were first considered in the 18th century by John Michell and Pierre-Simon Laplace.In 1916, Karl Schwarzschild found the first modern solution of general relativity that would characterize a black hole. David Finkelstein, in 1958, first published the interpretation of &quot;black hole&quot; as a region of space from which nothing can escape. Black holes were long considered a mathematical curiosity; it was not until the 1960s that theoretical work showed they were a generic prediction of general relativity. The discovery of neutron stars by Jocelyn Bell Burnell in 1967 sparked interest in gravitationally collapsed compact objects as a possible astrophysical reality. The first black hole known was Cygnus X-1, identified by several researchers independently in 1971.",
		"Black holes of stellar mass form when massive stars collapse at the end of their life cycle. After a black hole has formed, it can grow by absorbing mass from its surroundings. Supermassive black holes of millions of solar masses may form by absorbing other stars and merging with other black holes. There is consensus that supermassive black holes exist in the centers of most galaxies.",
		"The presence of a black hole can be inferred through its interaction with other matter and with electromagnetic radiation such as visible light. Any matter that falls onto a black hole can form an external accretion disk heated by friction, forming quasars, some of the brightest objects in the universe. Stars passing too close to a supermassive black hole can be shredded into streamers that shine very brightly before being &quot;swallowed.&quot; If other stars are orbiting a black hole, their orbits can be used to determine the black hole's mass and location. Such observations can be used to exclude possible alternatives such as neutron stars. In this way, astronomers have identified numerous stellar black hole candidates in binary systems and established that the radio source known as Sagittarius A*, at the core of the Milky Way galaxy, contains a supermassive black hole of about 4.3 million solar masses.",
		"Given the bizarre character of black holes, it was long questioned whether such objects could exist in nature or whether they were merely pathological solutions to Einstein's equations. Einstein himself wrongly thought black holes would not form, because he held that the angular momentum of collapsing particles would stabilize their motion at some radius. This led the general relativity community to dismiss all results to the contrary for many years. However, a minority of relativists continued to contend that black holes were physical objects, and by the end of the 1960s, they had persuaded most researchers in the field that there is no obstacle to the formation of an event horizon.",
		"Source: https://en.wikipedia.org/wiki/Black_hole"
	],
	[
		"Apollo 11",
		"Apollo11.jpg",
		[640, 482, -5],
		"Apollo 11 (July 16–24, 1969) was the American spaceflight that first landed humans on the Moon. Commander Neil Armstrong and Lunar Module Pilot Buzz Aldrin landed the Apollo Lunar Module Eagle on July 20, 1969, at 20:17 UTC, and Armstrong became the first person to step onto the Moon's surface six hours and 39 minutes later, on July 21 at 02:56 UTC. Aldrin joined him 19 minutes later, and they spent about two and a quarter hour together exploring the site they had named Tranquility Base upon landing. Armstrong and Aldrin collected 47.5 pounds (21.5 kg) of lunar material to bring back to Earth as pilot Michael Collins flew the Command Module Columbia in lunar orbit, and were on the Moon's surface for 21 hours, 36 minutes before lifting off to rejoin Columbia.",
		"Apollo 11 was launched by a Saturn V rocket from Kennedy Space Center on Merritt Island, Florida, on July 16 at 13:32 UTC, and it was the fifth crewed mission of NASA's Apollo program. The Apollo spacecraft had three parts: a command module (CM) with a cabin for the three astronauts, the only part that returned to Earth; a service module (SM), which supported the command module with propulsion, electrical power, oxygen, and water; and a lunar module (LM) that had two stages—a descent stage for landing on the Moon and an ascent stage to place the astronauts back into lunar orbit.",
		"After being sent to the Moon by the Saturn V's third stage, the astronauts separated the spacecraft from it and traveled for three days until they entered lunar orbit. Armstrong and Aldrin then moved into Eagle and landed in the Sea of Tranquility on July 20. The astronauts used Eagle's ascent stage to lift off from the lunar surface and rejoin Collins in the command module. They jettisoned Eagle before they performed the maneuvers that propelled Columbia out of the last of its 30 lunar orbits onto a trajectory back to Earth. They returned to Earth and splashed down in the Pacific Ocean on July 24 after more than eight days in space.",
		"Armstrong's first step onto the lunar surface was broadcast on live TV to a worldwide audience. He described the event as &quot;one small step for [a] man, one giant leap for mankind.&quot; Apollo 11 effectively proved U.S. victory in the Space Race to demonstrate spaceflight superiority, by fulfilling a national goal proposed in 1961 by President John F. Kennedy, &quot;before this decade is out, of landing a man on the Moon and returning him safely to the Earth.&quot;",
		"Source: https://en.wikipedia.org/wiki/Apollo_11"
	],
	[
		"Home Sweet Home",
		"HomeSweetHome.jpg",
		[640, 528],
		"Earth is the third planet from the Sun and the only astronomical object known to harbor life. This is enabled by Earth being a water world, the only one in the Solar System sustaining liquid surface water. Almost all of Earth's water is contained in its global ocean, covering 70.8% of Earth's crust. The remaining 29.2% of Earth's crust is land, most of which is in the form of continental landmasses within one hemisphere, Earth's land hemisphere. Most of Earth's land is somewhat humid and covered by vegetation, while large sheets of ice at Earth's polar deserts retain more water than Earth's groundwater, lakes, rivers and atmospheric water combined. Earth's crust consists of slowly moving tectonic plates, which interact to produce mountain ranges, volcanoes, and earthquakes. Earth has a liquid outer core that generates a magnetosphere capable of deflecting most of the destructive solar winds and cosmic radiation.",
		"Earth has a dynamic atmosphere, which sustains Earth's surface conditions and protects it from most meteoroids and UV-light at entry. It has a composition of primarily nitrogen and oxygen. Water vapor is widely present in the atmosphere, forming clouds that cover most of the planet. The water vapor acts as a greenhouse gas and, together with other greenhouse gases in the atmosphere, particularly carbon dioxide (CO2), creates the conditions for both liquid surface water and water vapor to persist via the capturing of energy from the Sun's light. This process maintains the current average surface temperature of 14.76 °C, at which water is liquid under atmospheric pressure. Differences in the amount of captured energy between geographic regions (as with the equatorial region receiving more sunlight than the polar regions) drive atmospheric and ocean currents, producing a global climate system with different climate regions, and a range of weather phenomena such as precipitation, allowing components such as nitrogen to cycle.",
		"Earth, like most other bodies in the Solar System, formed 4.5 billion years ago from gas in the early Solar System. During the first billion years of Earth's history, the ocean formed and then life developed within it. Life spread globally and has been altering Earth's atmosphere and surface, leading to the Great Oxidation Event two billion years ago. Humans emerged 300,000 years ago in Africa and have spread across every continent on Earth except for Antarctica. Humans depend on Earth's biosphere and natural resources for their survival but have increasingly impacted the planet's environment. Humanity's current impact on Earth's climate and biosphere is unsustainable, threatening the livelihood of humans and many other forms of life, and causing widespread extinctions.",
		"Source: https://en.wikipedia.org/wiki/Earth"
	],
	[
		"The Sun",
		"TheSun.jpg",
		[640, 499],
		"The Sun is the star at the center of the Solar System. It is a massive, hot ball of plasma, inflated and heated by energy produced by nuclear fusion reactions at its core. Part of this internal energy is emitted from its surface as light, ultraviolet, and infrared radiation, providing most of the energy for life on Earth.",
		"The enormous effect of the Sun on Earth has been recognized since prehistoric times; the Sun was thought of by some cultures as a deity. The synodic rotation of Earth and its orbit around the Sun are the basis of some solar calendars. The predominant calendar in use today is the Gregorian calendar, which is based upon the standard 16th-century interpretation of the Sun's observed movement as actual movement.",
		"One astronomical unit (about 150,000,000 km; 93,000,000 mi) is defined as the mean distance of the Sun's center to Earth's center, though the distance varies (by about +/- 2.5 million km or 1.55 million miles) as Earth moves from perihelion on about 3 January to aphelion on about 4 July. The distances can vary between 147,098,074 km (perihelion) and 152,097,701 km (aphelion), and extreme values can range from 147,083,346 km to 152,112,126 km. At its average distance, light travels from the Sun's horizon to Earth's horizon in about 8 minutes and 20 seconds, while light from the closest points of the Sun and Earth takes about two seconds less. The energy of this sunlight supports almost all life[c] on Earth by photosynthesis, and drives Earth's climate and weather.",
		"Source: https://en.wikipedia.org/wiki/Sun"
	],
	["@End"]
];
